spring:
  application:
    name: demo

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ProjectJava;encrypt=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

server:
  port: 8081

