spring:
  application:
    name: demo

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ProjectJava;encrypt=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

server:
  port: 8081
